baseURL: 'https://blog.zzjin.net'
languageCode: en-us
defaultContentLanguage: en
title: ZZJIN's 杂谈屋
theme: hermit

markup:
  highlight:
    guessSyntax: true
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

hasCJKLanguage: true # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit: 10 # Maximum number of items in the RSS feed.
# This message is only used by the RSS template.
copyright: >-
  This work is licensed under a Creative Commons Attribution-NonCommercial 4.0
  International License.
enableEmoji: true # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
permalinks:
  posts: '/:year/:month/:day/:title'
author:
  name: zzjin
taxonomies:
  tag: tags
  # Categories are disabled by default.
params:
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'
  # Metadata mostly used in document's head
  description: 了解人生与八卦的地方
  # images:
  #   - ''
  themeColor: '#494f5c'
  homeSubtitle: 了解人生与八卦的地方
  footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  bgImg: '' # Homepage background-image URL

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent: true # Set "text-align: justify" to `.content`.

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  social:
    - name: gitlab
      url: 'https://gitlab.com/zzjin'
    - name: github
      url: 'https://github.com/zzjin'
menu:
  main:
    - name: Posts
      url: posts/
      weight: 10
    - name: About
      url: about/
      weight: 20
